# this playbook implements the yum package manager to update the operating system packages
---
  - name: Update Yum Packages to their latest version(RHEL)
    yum:
      name: "*"
      state: latest
    when: ansible_os_family != "Debian"

  - name: Update apt packages to their latest version(Debian)
    command: sudo apt-get update -y
    when: ansible_os_family == "Debian"
