#this uninstalls Couchbase Server - NOTE: PROCEED WITH CAUTION!!!! THIS CANNOT BE UNDONE!!!!!
---
  - hosts: all
    become: true
    gather_facts: no
    vars_prompt:
      - name: uninstall_couchbase_server
        prompt: "Are you sure you want to uninstall Couchbase Server?(yes/no)"
        default: no
        confirm: yes 
        private: no

      - name: cannot_undo
        prompt: "Uninstalling Couchbase cannot be undone! Are you sure you want to continue?"
        default: no
        private: no
        when: uninstall_couchbase_server == 'yes'

    tasks:
      - name: Uninstall Couchbase Server
        action: ping
        when: cannot_undo == 'yes'
      - name: stop couchbase server service on each node
        command: systemctl stop couchbase-server
        register: stop_couchbase_server
        when: cannot_undo == 'yes'
      - name: remove all couchbase application packages
        command: rpm -e couchbase-server
        register: remove_packages
        when: cannot_undo == 'yes'
      - name: remove couchbase data and log directories
        command: rm -rf /opt/couchbase
        register: remove_dirs
        when: cannot_undo == 'yes'
             
      - debug: 
          msg: "{{stop_couchbase_server}}"
      - debug: 
          msg: "{{remove_packages}}"
      - debug:
          msg: "{{remove_dirs}}"

