#set up the other  data nodes in the cluster
---
  - hosts: couchbase_nodes[0]
    become: true
    tasks:

      - name: Rebalance all nodes into Couchbase Cluster
        shell:
          cmd: |
            /opt/couchbase/bin/couchbase-cli rebalance \
            --cluster {{hostvars[inventory_hostname].groups.couchbase_nodes[0]}} \
            --username "{{ couchbase_cluster.security.admin_user }}" \
            --password "{{ couchbase_cluster.security.admin_pwd }}" \
            --no-progress-bar

